version: '3'

services:
  broker-service:
    build:
      context: ./broker-service/
    restart: always
    ports:
      - "8080:80"

  auth-service:
    build:
      context: ./auth-service/
    restart: always
    ports:
      - "8081:80"   
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=postgres sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres 
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    depends_on:
      - auth-service