version: '3'

services:
  broker-service:
    build:
      context: ./broker-service/
    restart: always
    ports:
      - "8080:80"

  auth-service:
    build:
      context: ./auth-service/
    restart: always
    ports:
      - "8081:80"   
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=postgres sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    build:
      context: ./logger-service/
    restart: always
    ports:
      - "8082:80"

  mail-service:
    build:
      context: ./mail-service/
    restart: always
    ports:
      - "8083:80"
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      FROM_NAME: "admin"
      FROM_ADDRESS: "admin@example.com"

  listener-service:
    build: 
      context: ./listener-service
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.9.14-alpine
    ports:
      - "5672:5672"
    restart: always 
    volumes:
      - ./db-data/rabbitmq:/var/lib/rabbitmq

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres 
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    depends_on:
      - auth-service

  mongo:
    image: mongo:4.2.16-bionic
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo:/data/db
    depends_on:
      - logger-service
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"